name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.7.0"
          - "2.6"
          - "2.5"
          - "2.4"

    env:
      CLASSPATH: ""
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: ${{matrix.ruby}}
    - name: Install dependencies
      run: bundle install -j 4
    - name: Run tests
      run: bundle exec rspec
